#   Copyright 2022 Modelyst LLC
#   All Rights Reserved

---
default_stages: [commit, push]
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: forbid-tabs
      - id: insert-license
        name: Add license for all shell files
        exclude: ^\.github/.*$|docs_src/
        files: ^breeze$|^breeze-complete$|\.sh$|\.bash$|\.bats$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - license-templates/LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all python files
        exclude: ^\.github/.*$|docs_src/|^examples/
        types: [python]
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - license-templates/LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all yaml files
        exclude: ^\.github/.*$|^data/.*$
        types: [yaml]
        files: \.yml$|\.yaml$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - license-templates/LICENSE.txt
          - --fuzzy-match-generates-todo
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
        exclude: ^examples/simple
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^examples/simple
      - id: check-builtin-literals
        exclude: ^examples/simple
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args:
          - --remove
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.0
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: python-no-log-warn
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.6.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["-m", "3"]
        name: Run isort to sort imports
        files: \.py$
        # To keep consistent with the global isort skip config defined in setup.cfg
        exclude: ^build/.*$|^.tox/.*$|^venv/.*|docker/
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: Run pydocstyle
        args:
          - --config=setup.cfg
        exclude: ^examples/simple
  - repo: local
    hooks:
      - id: pydevd
        language: pygrep
        name: Check for pydevd debug statements accidentally left
        entry: "pydevd.*settrace\\("
        pass_filenames: true
        files: \.py$
      - id: no-relative-imports
        language: pygrep
        name: No relative imports
        description: Eventyst is to use absolute imports only
        entry: "^\\s*from\\s+\\."
        pass_filenames: true
        files: \.py$
        exclude: ^tests/|^examples/simple
      - id: consistent-pylint
        language: pygrep
        name: Check for inconsistent pylint disable/enable without space
        entry: "pylint:disable|pylint:enable"
        pass_filenames: true
        files: \.py$
      - id: autoflake
        name: Run autoflake
        entry: poetry run ./scripts/ci/autoflake.sh
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true
      - id: lint
        name: Run lint
        entry: poetry run ./scripts/ci/lint.sh
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true
      - id: flynt
        name: Convert to f-strings with flynt
        entry: flynt
        language: python
        language_version: python3
        additional_dependencies: ["flynt"]
        files: \.py$
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config", "setup.cfg", "src/eventyst"]
        files: \.py$
        exclude: ^docs_src/|^examples/simple
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.41.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
