#   Copyright 2022 Modelyst LLC
#   All Rights Reserved

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=b-1.mskue2testmsktest.57qrn4.c4.kafka.us-east-2.amazonaws.com:9098,b-2.mskue2testmsktest.57qrn4.c4.kafka.us-east-2.amazonaws.com:9097,b-3.mskue2testmsktest.57qrn4.c4.kafka.us-east-2.amazonaws.com:9096
      - KAFKA_CLUSTERS_0_NAME=kafka_cluster
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="mY*QApBmup*6y5!h%qNE";
      - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL_SSL
    ports:
      - "8080:8080"
