
#   Copyright 2023 Modelyst LLC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=b-1.mskue2testmsktest.57qrn4.c4.kafka.us-east-2.amazonaws.com:9098,b-2.mskue2testmsktest.57qrn4.c4.kafka.us-east-2.amazonaws.com:9097,b-3.mskue2testmsktest.57qrn4.c4.kafka.us-east-2.amazonaws.com:9096
      - KAFKA_CLUSTERS_0_NAME=kafka_cluster
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="mY*QApBmup*6y5!h%qNE";
      - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL_SSL
    ports:
      - "8080:8080"
